---
title: "R Notebook"
output: html_notebook
---

# Pré-processamento
```{r}
require(pacman)
p_load(caret,tidyverse,curl)

anime  <- read_csv("/home/adriano/Documents/MD/CLSS-11/Anime/anime.csv")
rating <- read_csv("/home/adriano/Documents/MD/CLSS-11/Anime/rating.csv")

anime  <- select(anime,c("anime_id","name"))
names(anime)[1] <- "id"

rating <- filter(rating,user_id  < 101)
#rating <- filter(rating,anime_id < 101)

rating$rating <- ifelse(rating$rating == -1,0,as.integer((rating$rating + 1)/2))

rating <- filter(rating,rating==5) %>% select(user_id,anime_id)
anime <- filter(anime, id %in% rating$anime_id)
```

```{r}
p_load(arules)

tableRatings <- table(rating)
colnames(tableRatings) <- anime$name


transacoes <- as(tableRatings[,1:50] > 0,"transactions")
itemSetFF <- eclat(transacoes,parameter = list(supp=0.02))
regrasFechadas <- ruleInduction(itemSetFF,confidence=.8)
```

```{r}
p_load(arulesViz)

print(head(quality(regrasFechadas)))
inspect(regrasFechadas[71,])
inspect(regrasFechadas[21,])
inspect(regrasFechadas[35,])
inspect(regrasFechadas[18,])
```
```{r}
plot(regrasFechadas, measure=c("support", "lift"), shading = "confidence", engine='interactive')
```

